version: "3.9"
services:
  cpp:
    build:
      context: .
      dockerfile: Dockerfile
    image: cpp
    container_name: cpp
    volumes:
      - type: bind
        source: .
        target: /home/cpp
    stdin_open: true
    tty: true
    working_dir: /home/cpp